# create a list of the count datasets you wish to analyse
# note. sometimes the cpm function can't be carried out on some of these count datasets since their counts are too low
# you'll hit an error such as "Error in cpm.default(x) : library sizes should be finite and non-negative"
# set the offending datasets to false here so the analysis can continue without these datasets
mirna_smrnaseq: true
mirna_excerpt: true
pirna_excerpt: true
trna_excerpt: true
circrna_excerpt: false
gencode_excerpt: false

# set the path to your metadata file
metadata_path: "/my_project/smncrna_analysis_template/metadata.csv"
