# choose the count datasets you wish to analyse
# note. sometimes the cpm function can't be carried out on some of these count datasets since their counts are
# too low you'll hit an error such as "Error in cpm.default(x) : library sizes should be finite and non-negative"
# set the offending datasets to false here so the analysis can continue without these datasets
mirna_smrnaseq: true
mirna_excerpt: true
pirna_excerpt: true
trna_excerpt: true
circrna_excerpt: false
gencode_excerpt: false

# set the path to your smncrna_analysis_template directory
#template_dir: "/my_project/smncrna_analysis_template/"

template_dir: "/NGS/scratch/KSCBIOM/HumanGenomics/smncrna_analysis_template"

# set the path to your metadata file
metadata_path: "/NGS/scratch/KSCBIOM/HumanGenomics/smncrna_analysis_template/metadata.csv"

# set the low sequencing read count flag, the number of reads at which you consider the sequencing read count
# to be low eg. 5000000 (5 million)
low_sequencing_read_count: 5000000

# specify the contrasts/treatment groups to compare
# in the following format:
# "first contrast" - "second contrast"
# one or multiple contrasts can be included here (maximum of 6)
contrasts: 
- "treatment1 - treatment2"
- "treatment3 - treatment4"

##### FILTERING ######

# filtering settings for limma/voom analysis

# minimum count required for at least some samples
# see info about this flag here: https://rdrr.io/bioc/edgeR/man/filterByExpr.html
# default is 10
min_count: 10

# minimum total count required
# see info about this flag here: https://rdrr.io/bioc/edgeR/man/filterByExpr.html
# default is 15
min_total_count: 15