---
title: "MDS"
author:
  # - Jane Doe^[Institution Two, jane@example.org]      # add report authors (uncomment if using)
  # - John Doe^[Institution One, john@example.org]      # add a second report author (uncomment if using)
date: "Date: `r base::format(Sys.time(), '%d/%m/%Y')`"
output:
  html_document:
    code_download: true
    code_folding: hide
    toc: false
  editor_options: 
    chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r setup, include=FALSE}
# setup default chunk settings
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, fig.align = "center", collapse = TRUE)

# activate renv
renv::activate()

# load libraries
library(plyr)
library(dplyr)
library(plotly)
library(gtools)
library(BiocManager)
library(limma)
library(textshape)
library(DT)
library(yaml)

# read in yaml config file specifying which rna species to analyse
config <- yaml::yaml.load_file("../config.yaml")

# create a vector defining the count datasets to analyse (that are set to TRUE) based on the yaml user configuration file
to_analyse <- config[c("mirna_smrnaseq",
                       "mirna_excerpt",
                       "pirna_excerpt",
                       "trna_excerpt",
                       "circrna_excerpt",
                       "gencode_excerpt")] %>%
  base::as.data.frame() %>%
  base::t() %>%
  base::as.data.frame() %>%
  tibble::rownames_to_column("rna_species") %>%
  dplyr::rename("analyse" = "V1") %>%
  tidyr::separate(rna_species, c("rna_species", "pipeline")) %>%
  dplyr::filter(analyse == TRUE) %>%
  dplyr::mutate(dataset_name = base::paste0(rna_species, "_", pipeline))

# also create a list for downstream filtering
to_analyse_list <- to_analyse %>%
  dplyr::pull(rna_species) %>%
  base::as.list()

# read in pre-prepared count data
counts <- utils::read.csv("../prepare_counts/counts.csv")

# read in metadata
metadata <- utils::read.csv(config$metadata_path)

# join with metadata
counts <- dplyr::left_join(counts, metadata, by = "sample")
```

```{bash}
# create a directory to write data to file (if it doesn't yet exist)
mkdir -p mds_results/mds/
```

```{r, eval = config$all_rnas, results = "asis"}
# pretty format the text for the header
to_analyse_pretty <- to_analyse %>%
  base::as.data.frame() %>%
  dplyr::mutate(rna_species = base::replace(rna_species, rna_species == "mirna", "miRNA's")) %>%
  dplyr::mutate(rna_species = base::replace(rna_species, rna_species == "mirna", "miRNA's")) %>%
  dplyr::mutate(rna_species = base::replace(rna_species, rna_species == "pirna", "piRNA's")) %>%
  dplyr::mutate(rna_species = base::replace(rna_species, rna_species == "trna", "tRNA's")) %>%
  dplyr::mutate(rna_species = base::replace(rna_species, rna_species == "circrna", "circRNA's")) %>%
  dplyr::mutate(rna_species = base::replace(rna_species, rna_species == "gencode", "gencode's")) %>%
  dplyr::mutate(pipeline = base::replace(pipeline, pipeline == "smrnaseq", "(smrnaseq)")) %>%
  dplyr::mutate(pipeline = base::replace(pipeline, pipeline == "excerpt", "(exceRpt)"))

# create a character string (from the list) of the rna species and pipelines being analysed to put into the header
rna_species_pretty <- to_analyse_pretty %>%
  dplyr::pull(rna_species) %>%
  base::as.list()

pipeline_pretty <- to_analyse_pretty %>%
  dplyr::pull(pipeline) %>%
  base::as.list()

to_analyse_pretty <- base::paste0(rna_species_pretty, " ", pipeline_pretty, collapse = " ")

# dynamically build up a header based on the rna species being analysed
base::cat(base::paste0("## All RNA's analysed: ", to_analyse_pretty, " ", "{.tabset .tabset-fade}"))
```

```{r, eval = config$all_rnas, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  # analyse/plot only the rna species the user has specified to analyse
  dplyr::filter(rna_species %in% to_analyse_list) %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_all_rnas.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$all_rnas, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             base::list(extend = "collection",
                                        buttons = c("csv", "excel", "pdf"),
                                        text = "Download"),
                             I("colvis"))))
```

```{r, eval = config$mirna_smrnaseq, results = "asis"}
# optionally include/print markdown header for this section if being analysed
base::cat("## miRNA's (smrnaseq)")
```

```{r, eval = config$mirna_smrnaseq, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "smrnaseq") %>%
  dplyr::filter(rna_species == "mirna") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_pirnas.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$mirna_smrnaseq, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             base::list(extend = "collection",
                                        buttons = c("csv", "excel", "pdf"),
                                        text = "Download"),
                             I("colvis"))))
```

```{r, eval = config$mirna_excerpt, results = "asis"}
# optionally include/print markdown header for this section if being analysed
base::cat("## miRNA's (excerpt)")
```

```{r, eval = config$mirna_excerpt, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  dplyr::filter(rna_species == "mirna") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_pirnas.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$mirna_excerpt, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             base::list(extend = "collection",
                                        buttons = c("csv", "excel", "pdf"),
                                        text = "Download"),
                             I("colvis"))))
```

```{r, eval = config$pirna_excerpt, results = "asis"}
# optionally include/print markdown header for this section if being analysed
base::cat("## piRNA's (excerpt)")
```

```{r, eval = config$pirna_excerpt, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  dplyr::filter(rna_species == "pirna") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_pirnas.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$pirna_excerpt, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             base::list(extend = "collection",
                                        buttons = c("csv", "excel", "pdf"),
                                        text = "Download"),
                             I("colvis"))))
```

```{r, eval = config$trna_excerpt, results = "asis"}
# optionally include/print markdown header for this section if being analysed
base::cat("## tRNA's (excerpt)")
```

```{r, eval = config$trna_excerpt, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  dplyr::filter(rna_species == "trna") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_trnas.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$trna_excerpt, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             base::list(extend = "collection",
                                        buttons = c("csv", "excel", "pdf"),
                                        text = "Download"),
                             I("colvis"))))
```

```{r, eval = config$circrna_excerpt, results = "asis"}
# optionally include/print markdown header for this section if being analysed
base::cat("## circRNA's (excerpt)")
```

```{r, eval = config$circrna_excerpt, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  dplyr::filter(rna_species == "circrna") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_circrnas.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$circrna_excerpt, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             base::list(extend = "collection",
                                        buttons = c("csv", "excel", "pdf"),
                                        text = "Download"),
                             I("colvis"))))
```

```{r, eval = config$gencode_excerpt, results = "asis"}
# optionally include/print markdown header for this section if being analysed
base::cat("## gencode's (excerpt)")
```

```{r, eval = config$gencode_excerpt, out.width = "100%"}
# calculate MDS
mds <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  dplyr::filter(rna_species == "gencode") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  limma::plotMDS(plot = FALSE)

# extract data and make into a dataframe for plotting
data <- base::cbind(mds$x, mds$y) %>%
  base::as.data.frame() %>%
  plyr::rename(c("V1" = "dim1")) %>%
  plyr::rename(c("V2" = "dim2")) %>%
  tibble::rownames_to_column("sample")

# save data to file
utils::write.csv(data, "mds_results/mds/mds_excerpt_gencode.csv", row.names = FALSE)

# bind data with metadata to get the treatment column
data <- dplyr::left_join(data, metadata, by = "sample")

# plot!
data %>%
  plotly::plot_ly(mode = "markers",
                  x = ~dim1,
                  y = ~dim2,
                  color = ~treatment,
                  hoverinfo = "text",
                  text = ~paste("</br> Sample:", sample,
                                "</br> Dim1:", base::format(dim1, big.mark = ",", scientific = FALSE, digits = 2),
                                "</br> Dim2:", base::format(dim2, big.mark = ",", scientific = FALSE, digits = 2))) %>%
  plotly::layout(xaxis = base::list(title = "Dim1"),
                 yaxis = base::list(title = "Dim2"))
```

```{r, eval = config$gencode_excerpt, out.width = "100%"}
# plot data in datatable
DT::datatable(data %>%
                dplyr::select(sample,
                              treatment,
                              dim1,
                              dim2),
              filter = "top",
              rownames = FALSE,
              colnames = c("Sample",
                           "Treatment",
                           "dim1",
                           "dim2"),
              extensions = base::list("ColReorder" = NULL,
                                      "Buttons" = NULL,
                                      "FixedColumns" = base::list(leftColumns=1)),
              options = base::list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = base::list(base::list(width = "200px", targets = 0)),
                lengthMenu = base::list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  base::list("copy",
                             list(extend = "collection",
                                  buttons = c("csv", "excel", "pdf"),
                                  text = "Download"),
                             I("colvis"))))
```

```{r, results = "hide"}
# save session info
base::writeLines(utils::capture.output(base::R.Version()), "R_version_info.txt")
base::writeLines(utils::capture.output(utils::sessionInfo()), "R_session_info.txt")
```
