---
title: "Data prep for app"
author:
  # - Jane Doe^[Institution Two, jane@example.org]      # add report authors (uncomment if using)
  # - John Doe^[Institution One, john@example.org]      # add a second report author (uncomment if using)
date: "Date: `r format(Sys.time(), '%d/%m/%Y')`"
output:
  html_document:
    code_download: true
    code_folding: show
  editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
# setup default chunk settings
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, fig.align = "center")
```

```{bash}
# create a directory to write data to file (if it doesn't yet exist)
mkdir -p data/
```

```{r}
##################################################################
##                  Setup & calculate PCA                       ##
##################################################################

# activate renv
renv::activate()

# load libraries
library(dplyr)
library(FactoMineR)
library(textshape)

# read in processed count data (processed in the differential expression document)
counts <- utils::read.csv("../prepare_counts/counts.csv")

# read in yaml config file
config <- yaml::yaml.load_file("../config.yaml")

# read in metadata
metadata <- utils::read.csv(config$metadata_path)

# calculate PCA
pca <- counts %>%
  dplyr::filter(pipeline == "excerpt") %>%
  dplyr::select(sample, rna, counts_per_million) %>%
  tidyr::pivot_wider(names_from = sample, values_from = counts_per_million) %>%
  textshape::column_to_rownames("rna") %>%
  base::as.matrix() %>%
  FactoMineR::PCA(graph = FALSE)

# extract the plotting coordinates from the PCA
scree_data <- pca$eig %>%
  base::as.data.frame() %>%
  tibble::rownames_to_column("component")

scree_data$component <- base::gsub("comp ", "", scree_data$component)

# extract the plotting coordinates from the PCA
variables_coords <- pca$var$coord %>%
  base::as.data.frame() %>%
  tibble::rownames_to_column("sample") %>%
  dplyr::rename_with(function(x) base::paste0(x, "_coord"), where(is.numeric))

# extract the cos values from the PCA
variables_cos <- pca$var$cos2 %>%
  base::as.data.frame() %>%
  tibble::rownames_to_column("sample") %>%
  dplyr::rename_with(function(x) base::paste0(x, "_cos"), where(is.numeric))

# join the two dataframes (plotting coordinates and cos values)
variables_data <- dplyr::left_join(variables_coords, variables_cos, by = "sample")

# append the metadata
variables_data <- dplyr::left_join(variables_data, metadata, by = "sample")

# extract the plotting coordinates from the PCA
individuals_coords <- pca$ind$coord %>%
  base::as.data.frame() %>%
  tibble::rownames_to_column("rna") %>%
  dplyr::rename_with(function(x) base::paste0(x, "_coord"), where(is.numeric))

# extract the cos values from the PCA
individuals_cos <- pca$ind$cos2 %>%
  base::as.data.frame() %>%
  tibble::rownames_to_column("rna") %>%
  dplyr::rename_with(function(x) base::paste0(x, "_cos"), where(is.numeric))

# join the two dataframes (plotting coordinates and cos values)
individuals_data <- dplyr::left_join(individuals_coords, individuals_cos, by = "rna")

##################################################################
##                Prepare PCA data for app                      ##
##################################################################

# make matrices for all combinations of dimensions so they are pre-calculated and make the shiny app quicker
# grab both the dimension and cos data for a given dimension pair and rename columns to generic names for the app to grab

# 1st dimension compared to everything
individuals_1_2 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.1"), contains("Dim.2"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "y")

individuals_1_3 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.1"), contains("Dim.3"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "y")

individuals_1_4 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.1"), contains("Dim.4"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "y")

individuals_1_5 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.1"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 2nd dimension compared to everything
individuals_2_3 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.2"), contains("Dim.3"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "y")

individuals_2_4 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.2"), contains("Dim.4"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "y")

individuals_2_5 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.2"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 3rd dimension compared to everything
individuals_3_4 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.3"), contains("Dim.4"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "y")

individuals_3_5 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.3"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 4th dimension compared to everything
individuals_4_5 <- individuals_data %>%
  dplyr::select(c(rna, contains("Dim.4"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 1st dimension compared to everything
variables_1_2 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.1"), contains("Dim.2"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "y")

variables_1_3 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.1"), contains("Dim.3"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "y")

variables_1_4 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.1"), contains("Dim.4"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "y")

variables_1_5 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.1"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.1", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 2nd dimension compared to everything
variables_2_3 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.2"), contains("Dim.3"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "y")

variables_2_4 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.2"), contains("Dim.4"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "y")

variables_2_5 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.2"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.2", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 3rd dimension compared to everything
variables_3_4 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.3"), contains("Dim.4"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "y")

variables_3_5 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.3"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.3", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

# 4th dimension compared to everything
variables_4_5 <- variables_data %>%
  dplyr::select(c(sample, treatment, contains("Dim.4"), contains("Dim.5"))) %>%
  dplyr::rename_with(gsub, pattern = "Dim.4", replacement = "x") %>%
  dplyr::rename_with(gsub, pattern = "Dim.5", replacement = "y")

#################################################################
##                        Write to file                        ##
#################################################################

# scree data
utils::write.csv(scree_data, "./data/scree.csv", row.names = FALSE)

# individuals (rna) data
utils::write.csv(individuals_1_2, "./data/individuals_1_2.csv", row.names = FALSE)
utils::write.csv(individuals_1_3, "./data/individuals_1_3.csv", row.names = FALSE)
utils::write.csv(individuals_1_4, "./data/individuals_1_4.csv", row.names = FALSE)
utils::write.csv(individuals_1_5, "./data/individuals_1_5.csv", row.names = FALSE)
utils::write.csv(individuals_2_3, "./data/individuals_2_3.csv", row.names = FALSE)
utils::write.csv(individuals_2_4, "./data/individuals_2_4.csv", row.names = FALSE)
utils::write.csv(individuals_2_5, "./data/individuals_2_5.csv", row.names = FALSE)
utils::write.csv(individuals_3_4, "./data/individuals_3_4.csv", row.names = FALSE)
utils::write.csv(individuals_3_5, "./data/individuals_3_5.csv", row.names = FALSE)
utils::write.csv(individuals_4_5, "./data/individuals_4_5.csv", row.names = FALSE)

# variables (samples) data
utils::write.csv(variables_1_2, "./data/variables_1_2.csv", row.names = FALSE)
utils::write.csv(variables_1_3, "./data/variables_1_3.csv", row.names = FALSE)
utils::write.csv(variables_1_4, "./data/variables_1_4.csv", row.names = FALSE)
utils::write.csv(variables_1_5, "./data/variables_1_5.csv", row.names = FALSE)
utils::write.csv(variables_2_3, "./data/variables_2_3.csv", row.names = FALSE)
utils::write.csv(variables_2_4, "./data/variables_2_4.csv", row.names = FALSE)
utils::write.csv(variables_2_5, "./data/variables_2_5.csv", row.names = FALSE)
utils::write.csv(variables_3_4, "./data/variables_3_4.csv", row.names = FALSE)
utils::write.csv(variables_3_5, "./data/variables_3_5.csv", row.names = FALSE)
utils::write.csv(variables_4_5, "./data/variables_4_5.csv", row.names = FALSE)
```

```{r, results = "hide"}
# save session info
base::writeLines(utils::capture.output(base::R.Version()), "R_version_info.txt")
base::writeLines(utils::capture.output(utils::sessionInfo()), "R_session_info.txt")
```
